### ISSUE TITLE
Does this works with Chinese?

### ISSUE THREAD

**Issue by tarvos21** [prakhar21/TextAugmentation-GPT2#1]
Does this works with Chinese text corpus? Thanks!

**Comment by prakhar21** [comment]
Yes, it would work. Replace the pretrained model with GPT2 chinese model and then fine tune the target text in the same way.

Thanks

**Comment by tarvos21** [comment]
thanks!

**Comment by xsyzka** [comment]
Where can I replace the Chinese pre-training model

**Comment by xsyzka** [comment]
Where can I replace the Chinese pre-training model, thank you
