### ISSUE TITLE
I am facing issues in train.py and also in generate.py

### ISSUE THREAD

**Issue by SarangShaikh201** [prakhar21/TextAugmentation-GPT2#5]
Can you please reply back so that I can discuss the problems I am facing.

train.py --> model = model.to(device) --> Error: name model is not defined
generated.py --> for pre-trained model I am getting issues for mismatch and checkpoints

Regards

**Comment by prakhar21** [comment]
for train.py please make the below-mentioned changes.

model = model.to(device)  -> MODEL = MODEL.to(device)
model.train() -> MODEL.train()

for generate.py, if you could paste detailed error that would help.

thank
